### ISSUE TITLE
Building VM for P4D2_2018_East returns errors

### ISSUE THREAD

**Issue by ederollora** [p4lang/tutorials#141]
After trying to build it with Vagrant the error at the end is this:

```
p4-tutorial: 970/970 Test #970: gtestp4c ......................................................................   Passed   15.56 sec
    p4-tutorial:
    p4-tutorial: 99% tests passed, 2 tests failed out of 970
    p4-tutorial:
    p4-tutorial: Label Time Summary:
    p4-tutorial:
    p4-tutorial: XFAIL        =  11.83 sec (6 tests)
    p4-tutorial:
    p4-tutorial: bmv2         = 1829.28 sec (281 tests)
    p4-tutorial:
    p4-tutorial: cpplint      = 130.48 sec (1 test)
    p4-tutorial:
    p4-tutorial: ebpf         =   9.16 sec (9 tests)
    p4-tutorial:
    p4-tutorial: gtest        =  15.56 sec (1 test)
    p4-tutorial: p14_to_16    = 1835.70 sec (181 tests)
    p4-tutorial: p4           = 953.47 sec (497 tests)
    p4-tutorial:
    p4-tutorial: Total Test time (real) = 2418.80 sec
    p4-tutorial:
    p4-tutorial: The following tests FAILED:
    p4-tutorial:        968 - p14_to_16/testdata/p4_14_samples/switch_20160226/switch.p4 (Timeout)
    p4-tutorial:        969 - p14_to_16/testdata/p4_14_samples/switch_20160512/switch.p4 (Timeout)
    p4-tutorial: Errors while running CTest
    p4-tutorial: CMakeFiles/check-all.dir/build.make:57: recipe for target 'CMakeFiles/check-all' failed
    p4-tutorial: CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/check-all.dir/all' failed
    p4-tutorial: make[3]: *** [CMakeFiles/check-all] Error 8
    p4-tutorial: make[2]: *** [CMakeFiles/check-all.dir/all] Error 2
    p4-tutorial: CMakeFiles/Makefile2:234: recipe for target 'CMakeFiles/check.dir/rule' failed
    p4-tutorial: Makefile:238: recipe for target 'check' failed
    p4-tutorial: make[1]: *** [CMakeFiles/check.dir/rule] Error 2
    p4-tutorial: make: *** [check] Error 2
The SSH command responded with a non-zero exit status. Vagrant
assumes that this means the command failed. The output for this command
should be in the log above. Please read the output to determine what
went wrong.
```
When trying to follow the basic exercise and trying `make run` the program complains about `p4c-bm2-ss` and this not being found. It is true, no command named `p4c-bm2-ss`. I guess that the error described above and this one could be related.
